import { Beneficiary, Volunteer } from '../types/beneficiary';

export const MOCK_VOLUNTEERS: Volunteer[] = [
  { id: 'vol-1', name: 'Priya Sharma', phone: '+91 98401 23456', neighborhood: 'Anna Nagar' },
  { id: 'vol-2', name: 'Rahul Nair', phone: '+91 98402 34567', neighborhood: 'T. Nagar' },
  { id: 'vol-3', name: 'Sneha Reddy', phone: '+91 98403 45678', neighborhood: 'Adyar' },
  { id: 'vol-4', name: 'Ananya Iyer', phone: '+91 98404 56789', neighborhood: 'Mylapore' },
  { id: 'vol-5', name: 'Karthik Raman', phone: '+91 98405 67890', neighborhood: 'Velachery' },
];

export const MOCK_BENEFICIARIES: Beneficiary[] = [
  {
    id: 'ben-001',
    name: 'Shanti Ramanathan',
    age: 78,
    gender: 'Female',
    phone: '+91 98840 11223',
    neighborhood: 'Mylapore',
    address: '14/2 South Mada Street, Mylapore, Chennai',
    livingSituation: 'Lives Alone',
    emergencyContact: {
      name: 'Venkatesh Ramanathan',
      relationship: 'Son (Living in Bangalore)',
      phone: '+91 99401 88776',
    },
    status: 'needs_attention',
    lastInteractionDate: '2026-07-28',
    daysSinceContact: 47,
    assignedVolunteer: MOCK_VOLUNTEERS[3], // Ananya Iyer
    needsAttentionReason: 'No contact in 45+ days. Missed two consecutive Sunday Chai & Chat circles.',
    notesSummary: 'Lives alone on 2nd floor with no elevator. Had mild arthritis flare-up last month.',
    joinedDate: '2024-03-15',
    interactions: [
      {
        id: 'int-101',
        beneficiaryId: 'ben-001',
        type: 'phone_call',
        date: '2026-07-28',
        loggedBy: 'Coordinator Maya',
        notes: 'Brief call. Shanti ji sounded fatigued. Mentioned knee stiffness preventing staircase descent.',
        previousStatus: 'active',
        newStatus: 'needs_attention',
        followUpRequired: true,
      },
      {
        id: 'int-102',
        beneficiaryId: 'ben-001',
        type: 'volunteer_checkin',
        date: '2026-07-12',
        loggedBy: 'Volunteer Ananya Iyer',
        notes: 'Delivered monthly ration and spent 45 minutes chatting about her Carnatic music interests.',
      },
      {
        id: 'int-103',
        beneficiaryId: 'ben-001',
        type: 'event_attendance',
        date: '2026-06-25',
        loggedBy: 'Staff Rajesh',
        notes: 'Attended Senior Citizens Yoga Session at Mylapore Community Center.',
      },
    ],
    activities: [
      { id: 'act-1', activityName: 'Chai & Chat Social Circle', date: '2026-06-15', category: 'social', attended: true },
      { id: 'act-2', activityName: 'Geriatric Health Camp', date: '2026-05-20', category: 'health_camp', attended: true },
      { id: 'act-3', activityName: 'Smartphone Basics (WhatsApp & UPI)', date: '2026-04-10', category: 'digital_literacy', attended: true },
    ],
  },
  {
    id: 'ben-002',
    name: 'K. S. Narayana Swamy',
    age: 82,
    gender: 'Male',
    phone: '+91 94441 55667',
    neighborhood: 'T. Nagar',
    address: '22 Raman Street, Near Panagal Park, T. Nagar, Chennai',
    livingSituation: 'Lives Alone',
    emergencyContact: {
      name: 'Dr. Sudha Swamy',
      relationship: 'Daughter',
      phone: '+91 98410 44332',
    },
    status: 'needs_attention',
    lastInteractionDate: '2026-08-05',
    daysSinceContact: 39,
    assignedVolunteer: MOCK_VOLUNTEERS[1], // Rahul Nair
    needsAttentionReason: 'No check-in in 39 days. Volunteer Rahul reported phone going unanswered.',
    notesSummary: 'Retired school headmaster. Enjoys reading history books. Hearing impairment on left ear.',
    joinedDate: '2023-11-10',
    interactions: [
      {
        id: 'int-201',
        beneficiaryId: 'ben-002',
        type: 'phone_call',
        date: '2026-08-05',
        loggedBy: 'Volunteer Rahul Nair',
        notes: 'Phone rang twice, disconnected. Need to dispatch a home check or coordinate with neighbor.',
        previousStatus: 'active',
        newStatus: 'needs_attention',
        followUpRequired: true,
      },
      {
        id: 'int-202',
        beneficiaryId: 'ben-002',
        type: 'home_visit',
        date: '2026-07-02',
        loggedBy: 'Volunteer Rahul Nair',
        notes: 'Home visit conducted. Found him in good spirits. Helped repair his digital radio.',
      },
    ],
    activities: [
      { id: 'act-4', activityName: 'Digital Literacy: Digital Banking & Cyber Safety', date: '2026-06-18', category: 'digital_literacy', attended: true },
      { id: 'act-5', activityName: 'Annual Eye Screening', date: '2026-03-12', category: 'health_camp', attended: true },
    ],
  },
  {
    id: 'ben-003',
    name: 'Devaki Ammal',
    age: 74,
    gender: 'Female',
    phone: '+91 97910 88990',
    neighborhood: 'Adyar',
    address: '8/1 Gandhi Nagar 3rd Crescent, Adyar, Chennai',
    livingSituation: 'With Spouse / Partner',
    emergencyContact: {
      name: 'R. Sundaram (Spouse)',
      relationship: 'Spouse (Age 79)',
      phone: '+91 97910 88991',
    },
    status: 'active',
    lastInteractionDate: '2026-09-10',
    daysSinceContact: 3,
    assignedVolunteer: MOCK_VOLUNTEERS[2], // Sneha Reddy
    notesSummary: 'Both spouses are active community garden volunteers. Very reliable participants.',
    joinedDate: '2024-01-20',
    interactions: [
      {
        id: 'int-301',
        beneficiaryId: 'ben-003',
        type: 'volunteer_checkin',
        date: '2026-09-10',
        loggedBy: 'Volunteer Sneha Reddy',
        notes: 'Weekly call check-in. Devaki ji confirmed attendance for upcoming community picnic.',
        newStatus: 'active',
      },
      {
        id: 'int-302',
        beneficiaryId: 'ben-003',
        type: 'event_attendance',
        date: '2026-08-28',
        loggedBy: 'Coordinator Maya',
        notes: 'Co-led the kolam drawing workshop for neighborhood elders.',
      },
    ],
    activities: [
      { id: 'act-6', activityName: 'Community Kitchen & Herb Garden', date: '2026-09-02', category: 'wellness', attended: true },
      { id: 'act-7', activityName: 'Senior Citizens Walkers Club', date: '2026-08-20', category: 'wellness', attended: true },
    ],
  },
  {
    id: 'ben-004',
    name: 'Syed Abdul Hameed',
    age: 85,
    gender: 'Male',
    phone: '+91 98845 66778',
    neighborhood: 'Triplicane',
    address: '45 Ellis Road, Triplicane, Chennai',
    livingSituation: 'Lives Alone',
    emergencyContact: {
      name: 'Farooq Hameed',
      relationship: 'Nephew',
      phone: '+91 98409 33221',
    },
    status: 'at_risk',
    lastInteractionDate: '2026-07-04',
    daysSinceContact: 71,
    assignedVolunteer: undefined, // Unassigned!
    needsAttentionReason: 'High Isolation Risk: 71 days without direct contact and NO assigned volunteer.',
    notesSummary: 'Has diabetes and hypertension. Living in independent room behind mosque.',
    joinedDate: '2023-08-14',
    interactions: [
      {
        id: 'int-401',
        beneficiaryId: 'ben-004',
        type: 'phone_call',
        date: '2026-07-04',
        loggedBy: 'Staff Rajesh',
        notes: 'Spoke briefly. Requested assistance with renewing his pensioner identity card.',
        previousStatus: 'active',
        newStatus: 'at_risk',
        followUpRequired: true,
      },
    ],
    activities: [
      { id: 'act-8', activityName: 'Pension & Civic Service Helpdesk', date: '2026-05-10', category: 'civic_services', attended: true },
    ],
  },
  {
    id: 'ben-005',
    name: 'Padmavathi Sundar',
    age: 71,
    gender: 'Female',
    phone: '+91 99620 33445',
    neighborhood: 'Anna Nagar',
    address: 'W-Block, 6th Main Road, Anna Nagar West, Chennai',
    livingSituation: 'Lives Alone',
    emergencyContact: {
      name: 'Gita Sundar',
      relationship: 'Daughter (Abroad - UK)',
      phone: '+44 7700 900123',
    },
    status: 'active',
    lastInteractionDate: '2026-09-08',
    daysSinceContact: 5,
    assignedVolunteer: MOCK_VOLUNTEERS[0], // Priya Sharma
    notesSummary: 'Loves teaching English and storytelling. Regular attendee of weekly virtual circle.',
    joinedDate: '2024-05-02',
    interactions: [
      {
        id: 'int-501',
        beneficiaryId: 'ben-005',
        type: 'volunteer_checkin',
        date: '2026-09-08',
        loggedBy: 'Volunteer Priya Sharma',
        notes: 'In-person doorstep visit with groceries. Padmavathi ji is doing very well.',
        newStatus: 'active',
      },
    ],
    activities: [
      { id: 'act-9', activityName: 'Storytelling & Memory Sharing Club', date: '2026-09-01', category: 'social', attended: true },
      { id: 'act-10', activityName: 'Chair Yoga & Breathing Exercises', date: '2026-08-22', category: 'wellness', attended: true },
    ],
  },
  {
    id: 'ben-006',
    name: 'G. Balasubramanian',
    age: 79,
    gender: 'Male',
    phone: '+91 98412 77889',
    neighborhood: 'Velachery',
    address: '12 Dhandeeswaram Nagar 4th Cross, Velachery, Chennai',
    livingSituation: 'Lives Alone',
    emergencyContact: {
      name: 'Ravi Bala',
      relationship: 'Son',
      phone: '+91 98410 99881',
    },
    status: 'needs_attention',
    lastInteractionDate: '2026-08-11',
    daysSinceContact: 33,
    assignedVolunteer: MOCK_VOLUNTEERS[4], // Karthik Raman
    needsAttentionReason: 'Over 30 days without contact. Missed routine blood pressure monitoring follow-up.',
    notesSummary: 'Former port trust employee. Mild memory issues reported by neighbors.',
    joinedDate: '2023-09-18',
    interactions: [
      {
        id: 'int-601',
        beneficiaryId: 'ben-006',
        type: 'event_attendance',
        date: '2026-08-11',
        loggedBy: 'Coordinator Maya',
        notes: 'Attended free BP check camp. Advised to consult physician for fluctuating readings.',
        previousStatus: 'active',
        newStatus: 'needs_attention',
        followUpRequired: true,
      },
    ],
    activities: [
      { id: 'act-11', activityName: 'Hypertension & Diabetes Check Camp', date: '2026-08-11', category: 'health_camp', attended: true },
    ],
  },
  {
    id: 'ben-007',
    name: 'Meenakshi Krishnan',
    age: 76,
    gender: 'Female',
    phone: '+91 94440 22334',
    neighborhood: 'Mylapore',
    address: '5 Kutchery Road, Mylapore, Chennai',
    livingSituation: 'Lives Alone',
    emergencyContact: {
      name: 'Arun Krishnan',
      relationship: 'Son (Living in Mumbai)',
      phone: '+91 98200 44556',
    },
    status: 'needs_attention',
    lastInteractionDate: '2026-08-01',
    daysSinceContact: 43,
    assignedVolunteer: MOCK_VOLUNTEERS[3], // Ananya Iyer
    needsAttentionReason: '43 days since last interaction. Needs volunteer visit to verify water supply issue.',
    notesSummary: 'Active temple visitor. Recently had issues with municipal water connection.',
    joinedDate: '2024-02-18',
    interactions: [
      {
        id: 'int-701',
        beneficiaryId: 'ben-007',
        type: 'phone_call',
        date: '2026-08-01',
        loggedBy: 'Staff Rajesh',
        notes: 'Reported water pipe leakage outside gate. Need local volunteer to follow up with Metro Water.',
        followUpRequired: true,
      },
    ],
    activities: [
      { id: 'act-12', activityName: 'Chai & Chat Social Circle', date: '2026-07-20', category: 'social', attended: true },
    ],
  },
  {
    id: 'ben-008',
    name: 'Joseph Vijayaraj',
    age: 81,
    gender: 'Male',
    phone: '+91 98408 12399',
    neighborhood: 'Adyar',
    address: '7 Canal Bank Road, Kasturba Nagar, Adyar, Chennai',
    livingSituation: 'Lives Alone',
    emergencyContact: {
      name: 'Mary Vijayaraj',
      relationship: 'Sister',
      phone: '+91 98400 66554',
    },
    status: 'at_risk',
    lastInteractionDate: '2026-06-20',
    daysSinceContact: 85,
    assignedVolunteer: MOCK_VOLUNTEERS[2], // Sneha Reddy
    needsAttentionReason: 'Critical gap: 85 days since last contact. Last check-in recorded reduced appetite.',
    notesSummary: 'Former teacher. Recovering from mild cataract surgery earlier this year.',
    joinedDate: '2023-05-12',
    interactions: [
      {
        id: 'int-801',
        beneficiaryId: 'ben-008',
        type: 'volunteer_checkin',
        date: '2026-06-20',
        loggedBy: 'Volunteer Sneha Reddy',
        notes: 'Doorstep visit. Mentioned feeling lonely since sister moved to outskirts.',
        previousStatus: 'active',
        newStatus: 'at_risk',
        followUpRequired: true,
      },
    ],
    activities: [
      { id: 'act-13', activityName: 'Geriatric Health Camp', date: '2026-04-14', category: 'health_camp', attended: true },
    ],
  },
  {
    id: 'ben-009',
    name: 'Lakshmi Rajagopalan',
    age: 73,
    gender: 'Female',
    phone: '+91 98842 55443',
    neighborhood: 'Anna Nagar',
    address: '18 2nd Avenue, Anna Nagar East, Chennai',
    livingSituation: 'With Spouse / Partner',
    status: 'active',
    lastInteractionDate: '2026-09-11',
    daysSinceContact: 2,
    assignedVolunteer: MOCK_VOLUNTEERS[0], // Priya Sharma
    notesSummary: 'Enjoys gardening and crafts. Attends almost every weekly digital literacy session.',
    joinedDate: '2024-04-12',
    interactions: [
      {
        id: 'int-901',
        beneficiaryId: 'ben-009',
        type: 'event_attendance',
        date: '2026-09-11',
        loggedBy: 'Coordinator Maya',
        notes: 'Attended Digital Literacy workshop: How to use DigiLocker and book auto via app.',
        newStatus: 'active',
      },
    ],
    activities: [
      { id: 'act-14', activityName: 'Digital Literacy: Ride Booking & Navigation', date: '2026-09-11', category: 'digital_literacy', attended: true },
      { id: 'act-15', activityName: 'Handicraft & Knitting Circle', date: '2026-08-30', category: 'social', attended: true },
    ],
  },
  {
    id: 'ben-010',
    name: 'Anthony D\'Souza',
    age: 84,
    gender: 'Male',
    phone: '+91 97909 33211',
    neighborhood: 'T. Nagar',
    address: '9 Habibullah Road, T. Nagar, Chennai',
    livingSituation: 'Lives Alone',
    status: 'inactive',
    lastInteractionDate: '2026-05-15',
    daysSinceContact: 121,
    assignedVolunteer: undefined,
    needsAttentionReason: 'No contact for 120+ days. Disconnected from all community programs.',
    notesSummary: 'Living alone. Relatives in Goa. Has not participated since May.',
    joinedDate: '2023-01-10',
    interactions: [
      {
        id: 'int-1001',
        beneficiaryId: 'ben-010',
        type: 'phone_call',
        date: '2026-05-15',
        loggedBy: 'Staff Rajesh',
        notes: 'Called regarding monsoon preparedness kit. No response recorded.',
        newStatus: 'inactive',
      },
    ],
    activities: [],
  },
  {
    id: 'ben-011',
    name: 'Rukmini Varadarajan',
    age: 77,
    gender: 'Female',
    phone: '+91 98403 77112',
    neighborhood: 'Mylapore',
    address: '34 Chitrakulam North Street, Mylapore, Chennai',
    livingSituation: 'Lives Alone',
    status: 'active',
    lastInteractionDate: '2026-09-07',
    daysSinceContact: 6,
    assignedVolunteer: MOCK_VOLUNTEERS[3], // Ananya Iyer
    notesSummary: 'Vibrant storyteller. Participates in intergenerational library reading program.',
    joinedDate: '2024-06-01',
    interactions: [
      {
        id: 'int-1101',
        beneficiaryId: 'ben-011',
        type: 'volunteer_checkin',
        date: '2026-09-07',
        loggedBy: 'Volunteer Ananya Iyer',
        notes: 'Monthly visit to deliver medicine kit and check wellness.',
      },
    ],
    activities: [
      { id: 'act-16', activityName: 'Chai & Chat Social Circle', date: '2026-08-25', category: 'social', attended: true },
    ],
  },
  {
    id: 'ben-012',
    name: 'C. V. Radhakrishnan',
    age: 80,
    gender: 'Male',
    phone: '+91 98411 99002',
    neighborhood: 'Velachery',
    address: '5 Gandhi Street, Baby Nagar, Velachery, Chennai',
    livingSituation: 'Lives Alone',
    status: 'needs_attention',
    lastInteractionDate: '2026-08-08',
    daysSinceContact: 36,
    assignedVolunteer: MOCK_VOLUNTEERS[4], // Karthik Raman
    needsAttentionReason: 'No check-in in 36 days. Needs volunteer to verify pension digital life certificate submission.',
    notesSummary: 'Pensioner. Needs assistance with Jeevan Pramaan digital submission.',
    joinedDate: '2023-10-05',
    interactions: [
      {
        id: 'int-1201',
        beneficiaryId: 'ben-012',
        type: 'phone_call',
        date: '2026-08-08',
        loggedBy: 'Volunteer Karthik Raman',
        notes: 'He asked about digital life certificate biometric scan dates.',
        followUpRequired: true,
      },
    ],
    activities: [
      { id: 'act-17', activityName: 'Pension & Civic Service Helpdesk', date: '2026-07-15', category: 'civic_services', attended: true },
    ],
  }
];
