import { Beneficiary, Volunteer, CommunityActivity } from '../types/beneficiary';
import { evaluateTriageSignal } from '../utils/triageLogic';

export const MOCK_VOLUNTEERS: Volunteer[] = [
  {
    id: 'vol-1',
    name: 'Priya Sharma',
    phone: '+91 98401 23456',
    neighborhood: 'Anna Nagar',
    skills: ['Tamil Fluency', 'First Aid Trained', 'Smartphone Coaching'],
    languages: ['Tamil', 'English', 'Hindi'],
    hoursContributed: 64,
    isSpotlight: true,
    spotlightBadge: 'Star Companion of the Month',
    elderTestimonial: {
      quote: 'Priya sits with me every Tuesday, sips chai, and patiently helped me video call my granddaughter in London for the first time.',
      elderName: 'Padmavathi Sundar (71)',
    },
  },
  {
    id: 'vol-2',
    name: 'Rahul Nair',
    phone: '+91 98402 34567',
    neighborhood: 'T. Nagar',
    skills: ['Malayalam', 'Elder Mobility Support', 'Home Safety Audits'],
    languages: ['Tamil', 'Malayalam', 'English'],
    hoursContributed: 42,
    elderTestimonial: {
      quote: 'Rahul repaired my old radio and checked all my door latches. Knowing someone is checking in makes sleeping at night so much calmer.',
      elderName: 'K. S. Narayana Swamy (82)',
    },
  },
  {
    id: 'vol-3',
    name: 'Sneha Reddy',
    phone: '+91 98403 45678',
    neighborhood: 'Adyar',
    skills: ['Empathetic Listening', 'Telugu', 'Health Camp Logistics'],
    languages: ['Telugu', 'Tamil', 'English'],
    hoursContributed: 88,
    isSpotlight: true,
    spotlightBadge: 'Monsoon Care Hero',
    elderTestimonial: {
      quote: 'During the heavy rains, Sneha brought hot soup and my heart medicines directly to my doorstep when water was knee-deep.',
      elderName: 'Joseph Vijayaraj (81)',
    },
  },
  {
    id: 'vol-4',
    name: 'Ananya Iyer',
    phone: '+91 98404 56789',
    neighborhood: 'Mylapore',
    skills: ['Carnatic Music Appreciation', 'Tamil', 'Ration Delivery'],
    languages: ['Tamil', 'Sanskrit', 'English'],
    hoursContributed: 56,
    isSpotlight: true,
    spotlightBadge: 'Heritage & Story Circle Guide',
    elderTestimonial: {
      quote: 'Ananya knows every Thyagaraja kriti. We spend hours talking about December music seasons of the 1960s. She feels like family.',
      elderName: 'Shanti Ramanathan (78)',
    },
  },
  {
    id: 'vol-5',
    name: 'Karthik Raman',
    phone: '+91 98405 67890',
    neighborhood: 'Velachery',
    skills: ['Pension Paperwork Guidance', 'UPI Safety', 'Wheelchair Support'],
    languages: ['Tamil', 'English'],
    hoursContributed: 35,
    elderTestimonial: {
      quote: 'Karthik helped me generate my digital life certificate without standing in a 3-hour post office line.',
      elderName: 'C. V. Radhakrishnan (80)',
    },
  },
  {
    id: 'vol-6',
    name: 'Dr. Kavita Natarajan',
    phone: '+91 98406 78901',
    neighborhood: 'Mylapore',
    skills: ['Geriatric Wellness', 'Nutritional Counseling', 'Tamil'],
    languages: ['Tamil', 'English'],
    hoursContributed: 50,
    isSpotlight: false,
    elderTestimonial: {
      quote: 'Dr. Kavita explains my medical reports with such patience and warmth. She treats every senior citizen with total dignity.',
      elderName: 'Rukmini Varadarajan (77)',
    },
  },
  {
    id: 'vol-7',
    name: 'Deepak Varma',
    phone: '+91 98407 89012',
    neighborhood: 'Adyar',
    skills: ['Library Book Delivery', 'Digital Literacy', 'Hindi'],
    languages: ['Hindi', 'Tamil', 'English'],
    hoursContributed: 29,
    elderTestimonial: {
      quote: 'Deepak brings me large-print books from the district library every fortnight.',
      elderName: 'Devaki Ammal (74)',
    },
  },
  {
    id: 'vol-8',
    name: 'Meera Chidambaram',
    phone: '+91 98408 90123',
    neighborhood: 'Anna Nagar',
    skills: ['Community Gardening', 'Art Therapy', 'Tamil'],
    languages: ['Tamil', 'English'],
    hoursContributed: 45,
    isSpotlight: false,
    elderTestimonial: {
      quote: 'Meera brought potted jasmine for my balcony and reignited my love for gardening after two years of grief.',
      elderName: 'Lakshmi Rajagopalan (73)',
    },
  },
];

export const MOCK_COMMUNITY_ACTIVITIES: CommunityActivity[] = [
  {
    id: 'act-1',
    title: 'Chai & Chat Senior Social Circle',
    category: 'social',
    categoryLabel: 'Social Companionship',
    categoryColor: 'bg-amber-50 text-amber-800 border-amber-200',
    date: 'Weekly • Every Sunday 4:30 PM',
    location: 'Mylapore Community Center & Temple Pavilion',
    attendeesCount: 28,
    status: 'Ongoing',
    story: 'Over fresh cardamom chai and warm samosas, 28 elders gathered to break the weekly silence of living alone. 82-year-old Swamy ji recited classic Bharathiyar verses from memory for the first time in three years, while two grandmothers who had not spoken to neighbors since the pandemic exchanged phone numbers to start morning walks together.',
    elderQuote: {
      quote: 'Coming here reminded me that I still have stories worth telling. When you live alone, silence becomes very loud. This Sunday circle feels like home.',
      author: 'Shanti Ramanathan (78)',
      neighborhood: 'Mylapore',
    },
    communityOutcome: '6 new peer-checkin buddy pairs formed; 100% of participants reported feeling happier and calmer.',
  },
  {
    id: 'act-2',
    title: 'Digital Bridges: Smartphone & Family Video Calling',
    category: 'digital_literacy',
    categoryLabel: 'Digital Literacy & Family Connection',
    categoryColor: 'bg-blue-50 text-blue-800 border-blue-200',
    date: '2026-09-11',
    location: 'Anna Nagar Public Library Seminar Room',
    attendeesCount: 19,
    status: 'Completed',
    story: 'Student volunteers sat 1-on-1 with elders to demystify smartphones. Instead of rushed lessons, coordinators taught only three things that truly mattered to them: how to place a WhatsApp video call to grandchildren abroad, how to listen to devotional morning podcasts, and how to spot digital scam calls.',
    elderQuote: {
      quote: 'My children live in the UK. Today, with Priya holding my hand, I saw my 4-year-old grandson wave at me through the screen without needing anyone else to dial for me.',
      author: 'Padmavathi Sundar (71)',
      neighborhood: 'Anna Nagar',
    },
    communityOutcome: '19 elders learned self-sufficient video calling; 0 participants fell for subsequent spoofing messages.',
  },
  {
    id: 'act-3',
    title: 'Doorstep Geriatric Health & Free Blood Pressure Camp',
    category: 'health_camp',
    categoryLabel: 'Preventative Health & Dignity',
    categoryColor: 'bg-emerald-50 text-emerald-800 border-emerald-200',
    date: '2026-09-18 (Upcoming)',
    location: 'Adyar Primary Community Clinic & Doorstep Mobile Van',
    attendeesCount: 35,
    status: 'Registration Open',
    story: 'Many elderly residents avoid visiting hospitals because of steep steps and confusing ticket queues. Saathi brings geriatric doctors, free blood pressure monitoring, random blood sugar tests, and eye screenings directly into the neighborhood pavilion and doorstep van for bedridden elders.',
    elderQuote: {
      quote: 'Going to the government hospital with my knee pain is an ordeal. Having a doctor greet me with a smile right down my lane makes me feel truly cared for.',
      author: 'G. Balasubramanian (79)',
      neighborhood: 'Velachery',
    },
    communityOutcome: 'Early detection of uncontrolled hypertension in 7 solo elders, immediate physician follow-up arranged.',
  },
  {
    id: 'act-4',
    title: 'Senior Citizen Pension & Jeevan Pramaan Digital Helpdesk',
    category: 'civic_services',
    categoryLabel: 'Civic Rights & Independence',
    categoryColor: 'bg-indigo-50 text-indigo-800 border-indigo-200',
    date: 'Monthly • 1st Saturday',
    location: 'T. Nagar Seva Samithi Hall',
    attendeesCount: 16,
    status: 'Completed',
    story: 'Every winter, thousands of elderly pensioners face immense stress submitting their annual life certificates. Saathi volunteers set up biometric iris and face-authentication scanners so elders could complete their pension verification in 4 minutes with dignified seating and refreshments.',
    elderQuote: {
      quote: 'Last year my pension was withheld for three months because my fingerprints failed. The young volunteers at Saathi resolved it with facial recognition in minutes.',
      author: 'C. V. Radhakrishnan (80)',
      neighborhood: 'Velachery',
    },
    communityOutcome: '16 senior pensions safely renewed without delays or bureaucratic harassment.',
  },
  {
    id: 'act-5',
    title: 'Memory Lane: Intergenerational Storytelling Circle',
    category: 'social',
    categoryLabel: 'Intergenerational Connection',
    categoryColor: 'bg-purple-50 text-purple-800 border-purple-200',
    date: '2026-09-05',
    location: 'Triplicane Heritage Library Courtyard',
    attendeesCount: 22,
    status: 'Completed',
    story: 'Local high school students sat in a circle with elders to record oral histories of 1950s Chennai. The students brought handmade greeting cards, and elders shared memories of handloom weavers, tramways, and historic family recipes.',
    elderQuote: {
      quote: 'The youngsters listened to me as if I was reading them an adventure story. For three hours, I was not an old sick man; I was a storyteller.',
      author: 'Syed Abdul Hameed (85)',
      neighborhood: 'Triplicane',
    },
    communityOutcome: '12 young volunteers committed to weekly companion check-in calls with participating elders.',
  },
  {
    id: 'act-6',
    title: 'Chair Yoga, Gentle Breathing & Laughter Circle',
    category: 'wellness',
    categoryLabel: 'Holistic Well-being',
    categoryColor: 'bg-teal-50 text-teal-800 border-teal-200',
    date: 'Bi-Weekly • Wednesday 9:00 AM',
    location: 'Adyar River Park Amphitheatre',
    attendeesCount: 24,
    status: 'Ongoing',
    story: 'Specially adapted for arthritis and reduced joint mobility, this morning session focuses on diaphragmatic breathing, seated neck rolls, and lighthearted laughter therapy under the shade of ancient banyan trees.',
    elderQuote: {
      quote: 'I used to wake up with stiff joints and a heavy heart. Breathing the morning ocean breeze with my friends gives me vitality for the whole week.',
      author: 'Devaki Ammal (74)',
      neighborhood: 'Adyar',
    },
    communityOutcome: 'Documented improvements in sleep quality and mood reported across 85% of regulars.',
  },
];

const RAW_BENEFICIARIES: Omit<Beneficiary, 'triageSignal'>[] = [
  {
    id: 'ben-001',
    name: 'Shanti Ramanathan',
    age: 78,
    gender: 'Female',
    phone: '+91 98840 11223',
    neighborhood: 'Mylapore',
    address: '14/2 South Mada Street, Mylapore, Chennai',
    livingSituation: 'Lives Alone',
    emergencyContact: {
      name: 'Venkatesh Ramanathan',
      relationship: 'Son (Living in Bangalore)',
      phone: '+91 99401 88776',
    },
    status: 'needs_attention',
    lastInteractionDate: '2026-07-28',
    daysSinceContact: 47,
    assignedVolunteer: MOCK_VOLUNTEERS[3], // Ananya Iyer
    needsAttentionReason: 'No contact in 47 days. Severe knee arthritis flare-up has prevented staircase descent from 2nd-floor home.',
    lifeStorySnippet: 'Former Carnatic vocal teacher and avid reader. After losing her husband 4 years ago, her living room is filled with classic music recordings and family portraits.',
    healthRemarks: 'Severe knee arthritis, mobility restricted to indoors, 2nd-floor walk-up with no elevator.',
    notesSummary: 'Gentle, polite, but very proud. Tends to downplay physical pain to avoid troubling volunteers. Needs proactive in-person check-in.',
    joinedDate: '2024-03-15',
    interactions: [
      {
        id: 'int-101',
        beneficiaryId: 'ben-001',
        type: 'phone_call',
        date: '2026-07-28',
        loggedBy: 'Coordinator Maya',
        notes: 'Sounded fatigued and quiet. Admitted knee stiffness made climbing down stairs impossible this month. Missed two Chai circles.',
        previousStatus: 'active',
        newStatus: 'needs_attention',
        followUpRequired: true,
      },
      {
        id: 'int-102',
        beneficiaryId: 'ben-001',
        type: 'volunteer_checkin',
        date: '2026-07-12',
        loggedBy: 'Volunteer Ananya Iyer',
        notes: 'Doorstep visit. Delivered weekly groceries, spent 40 minutes listening to vintage Carnatic ragas together. Spirits were high.',
      },
      {
        id: 'int-103',
        beneficiaryId: 'ben-001',
        type: 'event_attendance',
        date: '2026-06-25',
        loggedBy: 'Staff Rajesh',
        notes: 'Attended Sunday Chai & Chat circle. Smiled throughout and recited an old poem.',
      },
    ],
    activities: [
      { id: 'act-1', activityName: 'Chai & Chat Social Circle', date: '2026-06-25', category: 'social', attended: true, personalExperience: 'Recited vintage devotional songs with neighborhood friends.' },
      { id: 'act-3', activityName: 'Geriatric Health Camp', date: '2026-05-20', category: 'health_camp', attended: true, personalExperience: 'Received joint relief ointment and blood pressure screening.' },
    ],
  },
  {
    id: 'ben-002',
    name: 'K. S. Narayana Swamy',
    age: 82,
    gender: 'Male',
    phone: '+91 94441 55667',
    neighborhood: 'T. Nagar',
    address: '22 Raman Street, Near Panagal Park, T. Nagar, Chennai',
    livingSituation: 'Lives Alone',
    emergencyContact: {
      name: 'Dr. Sudha Swamy',
      relationship: 'Daughter (Practicing Physician in Salem)',
      phone: '+91 98410 44332',
    },
    status: 'needs_attention',
    lastInteractionDate: '2026-08-05',
    daysSinceContact: 39,
    assignedVolunteer: MOCK_VOLUNTEERS[1], // Rahul Nair
    needsAttentionReason: 'No check-in in 39 days. Last phone call rang twice and disconnected. Left ear hearing impairment.',
    lifeStorySnippet: 'Retired government high school headmaster. Passionate about Tamil literature, historical biographies, and evening radio news.',
    healthRemarks: 'Partial left ear hearing loss, mild hand tremors, prone to skipping meals when living alone.',
    notesSummary: 'Very articulate when engaged. Needs someone to physically knock loudly on his door since landline volume is often not heard.',
    joinedDate: '2023-11-10',
    interactions: [
      {
        id: 'int-201',
        beneficiaryId: 'ben-002',
        type: 'phone_call',
        date: '2026-08-05',
        loggedBy: 'Volunteer Rahul Nair',
        notes: 'Phone rang twice with no pickup. Need neighbor or volunteer physical check to verify safety.',
        previousStatus: 'active',
        newStatus: 'needs_attention',
        followUpRequired: true,
      },
      {
        id: 'int-202',
        beneficiaryId: 'ben-002',
        type: 'home_visit',
        date: '2026-07-02',
        loggedBy: 'Volunteer Rahul Nair',
        notes: 'Visited home. Swamy sir was in good health. Helped him fix his transistor radio batteries.',
      },
    ],
    activities: [
      { id: 'act-2', activityName: 'Digital Bridges: Smartphone & Safety', date: '2026-06-18', category: 'digital_literacy', attended: true },
    ],
  },
  {
    id: 'ben-003',
    name: 'Devaki Ammal',
    age: 74,
    gender: 'Female',
    phone: '+91 97910 88990',
    neighborhood: 'Adyar',
    address: '8/1 Gandhi Nagar 3rd Crescent, Adyar, Chennai',
    livingSituation: 'With Spouse / Partner',
    emergencyContact: {
      name: 'R. Sundaram',
      relationship: 'Spouse (Age 79)',
      phone: '+91 97910 88991',
    },
    status: 'active',
    lastInteractionDate: '2026-09-10',
    daysSinceContact: 3,
    assignedVolunteer: MOCK_VOLUNTEERS[2], // Sneha Reddy
    lifeStorySnippet: 'Matriarch of a close-knit neighborhood, co-founder of the local senior herb garden. Loves welcoming new volunteers.',
    healthRemarks: 'Mild hypertension managed with medication; active and mobile.',
    notesSummary: 'Devaki ji and her husband Sundaram are anchors of our Adyar circle. They actively encourage shy elders to attend.',
    joinedDate: '2024-01-20',
    interactions: [
      {
        id: 'int-301',
        beneficiaryId: 'ben-003',
        type: 'volunteer_checkin',
        date: '2026-09-10',
        loggedBy: 'Volunteer Sneha Reddy',
        notes: 'Weekly check-in. Devaki ji confirmed attendance for upcoming weekend chai circle.',
        newStatus: 'active',
      },
    ],
    activities: [
      { id: 'act-6', activityName: 'Chair Yoga & Gentle Breathing', date: '2026-09-02', category: 'wellness', attended: true },
      { id: 'act-1', activityName: 'Chai & Chat Social Circle', date: '2026-08-20', category: 'social', attended: true },
    ],
  },
  {
    id: 'ben-004',
    name: 'Syed Abdul Hameed',
    age: 85,
    gender: 'Male',
    phone: '+91 98845 66778',
    neighborhood: 'Triplicane',
    address: '45 Ellis Road, Triplicane, Chennai',
    livingSituation: 'Lives Alone',
    emergencyContact: {
      name: 'Farooq Hameed',
      relationship: 'Nephew',
      phone: '+91 98409 33221',
    },
    status: 'at_risk',
    lastInteractionDate: '2026-07-04',
    daysSinceContact: 71,
    assignedVolunteer: undefined, // Unassigned!
    needsAttentionReason: 'Critical Isolation Risk: 71 days without direct contact and NO assigned volunteer companion.',
    lifeStorySnippet: 'Master bookbinder who worked in heritage printing presses near Big Mosque. Lives alone in a quiet room behind the mosque courtyard.',
    healthRemarks: 'Diabetic, severe age-related frailty, reduced appetite, vision impairment in bright light.',
    notesSummary: 'Expressed feeling forgotten in last interaction. Urgently needs a local Triplicane volunteer companion to rebuild regular contact.',
    joinedDate: '2023-08-14',
    interactions: [
      {
        id: 'int-401',
        beneficiaryId: 'ben-004',
        type: 'phone_call',
        date: '2026-07-04',
        loggedBy: 'Staff Rajesh',
        notes: 'Spoke briefly. Sounded weak. Mentioned trouble walking to the local medical dispensary.',
        previousStatus: 'active',
        newStatus: 'at_risk',
        followUpRequired: true,
      },
    ],
    activities: [
      { id: 'act-5', activityName: 'Memory Lane Storytelling Circle', date: '2026-05-10', category: 'social', attended: true },
    ],
  },
  {
    id: 'ben-005',
    name: 'Padmavathi Sundar',
    age: 71,
    gender: 'Female',
    phone: '+91 99620 33445',
    neighborhood: 'Anna Nagar',
    address: 'W-Block, 6th Main Road, Anna Nagar West, Chennai',
    livingSituation: 'Lives Alone',
    emergencyContact: {
      name: 'Gita Sundar',
      relationship: 'Daughter (Living in London, UK)',
      phone: '+44 7700 900123',
    },
    status: 'active',
    lastInteractionDate: '2026-09-08',
    daysSinceContact: 5,
    assignedVolunteer: MOCK_VOLUNTEERS[0], // Priya Sharma
    lifeStorySnippet: 'Former primary school English educator. Deeply affectionate, loves storytelling, and makes traditional hand-knitted woolen scarves.',
    healthRemarks: 'Mild blood pressure, fully mobile and active.',
    notesSummary: 'Priya Sharma visits her weekly. The video calling workshop transformed her emotional outlook as she now speaks to her grandson weekly.',
    joinedDate: '2024-05-02',
    interactions: [
      {
        id: 'int-501',
        beneficiaryId: 'ben-005',
        type: 'volunteer_checkin',
        date: '2026-09-08',
        loggedBy: 'Volunteer Priya Sharma',
        notes: 'Doorstep visit. Padmavathi ji proudly showed photos of her video call with family in London. In great spirits.',
        newStatus: 'active',
      },
    ],
    activities: [
      { id: 'act-2', activityName: 'Digital Bridges: Smartphone Workshop', date: '2026-09-11', category: 'digital_literacy', attended: true },
    ],
  },
  {
    id: 'ben-006',
    name: 'G. Balasubramanian',
    age: 79,
    gender: 'Male',
    phone: '+91 98412 77889',
    neighborhood: 'Velachery',
    address: '12 Dhandeeswaram Nagar 4th Cross, Velachery, Chennai',
    livingSituation: 'Lives Alone',
    emergencyContact: {
      name: 'Ravi Bala',
      relationship: 'Son (Working in Hyderabad)',
      phone: '+91 98410 99881',
    },
    status: 'needs_attention',
    lastInteractionDate: '2026-08-11',
    daysSinceContact: 33,
    assignedVolunteer: MOCK_VOLUNTEERS[4], // Karthik Raman
    needsAttentionReason: '33 days since last contact. Recorded fluctuating blood pressure; missed scheduled medical follow-up.',
    lifeStorySnippet: 'Former port trust accountant. Meticulous with records, loves chess and morning walks along the lake.',
    healthRemarks: 'Fluctuating blood pressure, forgetfulness regarding medicine timings.',
    notesSummary: 'Needs volunteer Karthik to coordinate a doorstep pill organizer review with local pharmacy partner.',
    joinedDate: '2023-09-18',
    interactions: [
      {
        id: 'int-601',
        beneficiaryId: 'ben-006',
        type: 'event_attendance',
        date: '2026-08-11',
        loggedBy: 'Coordinator Maya',
        notes: 'Attended free BP check camp. Doctor noted elevated readings and advised re-check in 2 weeks.',
        previousStatus: 'active',
        newStatus: 'needs_attention',
        followUpRequired: true,
      },
    ],
    activities: [
      { id: 'act-3', activityName: 'Geriatric Health Camp', date: '2026-08-11', category: 'health_camp', attended: true },
    ],
  },
  {
    id: 'ben-007',
    name: 'Joseph Vijayaraj',
    age: 81,
    gender: 'Male',
    phone: '+91 98408 12399',
    neighborhood: 'Adyar',
    address: '7 Canal Bank Road, Kasturba Nagar, Adyar, Chennai',
    livingSituation: 'Lives Alone',
    emergencyContact: {
      name: 'Mary Vijayaraj',
      relationship: 'Sister (Lives in Tambaram)',
      phone: '+91 98400 66554',
    },
    status: 'at_risk',
    lastInteractionDate: '2026-06-20',
    daysSinceContact: 85,
    assignedVolunteer: MOCK_VOLUNTEERS[2], // Sneha Reddy
    needsAttentionReason: 'Severe gap: 85 days without direct contact. Previous visit noted diminished appetite and profound loneliness.',
    lifeStorySnippet: 'Former physics tutor. Lives in ground floor room. His daily routine consists of tending to potted plants on his veranda.',
    healthRemarks: 'Recovering from mild cataract surgery, reported loss of appetite and low energy.',
    notesSummary: 'High priority for in-person companion outreach. Sneha Reddy assigned to visit with nutritious meals.',
    joinedDate: '2023-05-12',
    interactions: [
      {
        id: 'int-801',
        beneficiaryId: 'ben-007',
        type: 'volunteer_checkin',
        date: '2026-06-20',
        loggedBy: 'Volunteer Sneha Reddy',
        notes: 'Doorstep check. Joseph sir was quiet and ate very little. Expressed feeling isolated since his sister moved.',
        previousStatus: 'active',
        newStatus: 'at_risk',
        followUpRequired: true,
      },
    ],
    activities: [
      { id: 'act-3', activityName: 'Geriatric Health Camp', date: '2026-04-14', category: 'health_camp', attended: true },
    ],
  },
  {
    id: 'ben-008',
    name: 'Anthony D\'Souza',
    age: 84,
    gender: 'Male',
    phone: '+91 97909 33211',
    neighborhood: 'T. Nagar',
    address: '9 Habibullah Road, T. Nagar, Chennai',
    livingSituation: 'Lives Alone',
    status: 'inactive',
    lastInteractionDate: '2026-05-15',
    daysSinceContact: 121,
    assignedVolunteer: undefined,
    needsAttentionReason: 'Over 120 days disconnected. All relatives live out of state. Needs re-engagement evaluation.',
    lifeStorySnippet: 'Former railway signal technician. Skilled harmonica player, lived in T. Nagar for over 55 years.',
    healthRemarks: 'Mild memory lapses, arthritis.',
    notesSummary: 'Completely disconnected since May. Coordinator needs to do home verification visit with local church representative.',
    joinedDate: '2023-01-10',
    interactions: [],
    activities: [],
  },
];

// Enrich with deterministic triage logic
export const MOCK_BENEFICIARIES: Beneficiary[] = RAW_BENEFICIARIES.map(b => ({
  ...b,
  triageSignal: evaluateTriageSignal(b),
}));
