export const SEED_VOLUNTEERS = [
  {
    id: 'vol-1',
    name: 'Priya Sharma',
    phone: '+91 98401 23456',
    neighborhood: 'Anna Nagar',
    skills: ['Tamil Fluency', 'First Aid Trained', 'Smartphone Coaching'],
    languages: ['Tamil', 'English', 'Hindi'],
    hoursContributed: 64,
    role: 'Morning Companion Champion',
    isSpotlight: true,
    spotlightBadge: 'Star Companion of the Month',
    elderTestimonial: {
      quote: 'Priya sits with me every Tuesday, sips chai, and patiently helped me video call my granddaughter in London for the first time.',
      elderName: 'Padmavathi Sundar (71)',
    },
  },
  {
    id: 'vol-2',
    name: 'Rahul Nair',
    phone: '+91 98402 34567',
    neighborhood: 'T. Nagar',
    skills: ['Malayalam', 'Elder Mobility Support', 'Home Safety Audits'],
    languages: ['Tamil', 'Malayalam', 'English'],
    hoursContributed: 42,
    role: 'Neighborhood Mobility Liaison',
    elderTestimonial: {
      quote: 'Rahul repaired my old radio and checked all my door latches. Knowing someone is checking in makes sleeping at night so much calmer.',
      elderName: 'K. S. Narayana Swamy (82)',
    },
  },
  {
    id: 'vol-3',
    name: 'Sneha Reddy',
    phone: '+91 98403 45678',
    neighborhood: 'Adyar',
    skills: ['Empathetic Listening', 'Telugu', 'Health Camp Logistics'],
    languages: ['Telugu', 'Tamil', 'English'],
    hoursContributed: 88,
    role: 'Elder Wellness Advocate',
    isSpotlight: true,
    spotlightBadge: 'Monsoon Care Hero',
    elderTestimonial: {
      quote: 'During the heavy rains, Sneha brought hot soup and my heart medicines directly to my doorstep when water was knee-deep.',
      elderName: 'Joseph Vijayaraj (81)',
    },
  },
  {
    id: 'vol-4',
    name: 'Ananya Iyer',
    phone: '+91 98404 56789',
    neighborhood: 'Mylapore',
    skills: ['Carnatic Music Appreciation', 'Tamil', 'Ration Delivery'],
    languages: ['Tamil', 'Sanskrit', 'English'],
    hoursContributed: 56,
    role: 'Heritage & Story Circle Guide',
    isSpotlight: true,
    spotlightBadge: 'Cultural Circle Host',
    elderTestimonial: {
      quote: 'Ananya knows every Thyagaraja kriti. We spend hours talking about December music seasons of the 1960s. She feels like family.',
      elderName: 'Shanti Ramanathan (78)',
    },
  },
  {
    id: 'vol-5',
    name: 'Karthik Raman',
    phone: '+91 98405 67890',
    neighborhood: 'Velachery',
    skills: ['Pension Paperwork Guidance', 'UPI Safety', 'Wheelchair Support'],
    languages: ['Tamil', 'English'],
    hoursContributed: 35,
    role: 'Civic Access Volunteer',
    elderTestimonial: {
      quote: 'Karthik helped me generate my digital life certificate without standing in a 3-hour post office line.',
      elderName: 'C. V. Radhakrishnan (80)',
    },
  },
  {
    id: 'vol-6',
    name: 'Dr. Kavita Natarajan',
    phone: '+91 98406 78901',
    neighborhood: 'Mylapore',
    skills: ['Geriatric Wellness', 'Nutritional Counseling', 'Tamil'],
    languages: ['Tamil', 'English'],
    hoursContributed: 50,
    role: 'Community Health Partner',
    elderTestimonial: {
      quote: 'Dr. Kavita explains my medical reports with such patience and warmth. She treats every senior citizen with total dignity.',
      elderName: 'Rukmini Varadarajan (77)',
    },
  },
  {
    id: 'vol-7',
    name: 'Deepak Varma',
    phone: '+91 98407 89012',
    neighborhood: 'Adyar',
    skills: ['Library Book Delivery', 'Digital Literacy', 'Hindi'],
    languages: ['Hindi', 'Tamil', 'English'],
    hoursContributed: 29,
    role: 'Book & Reading Companion',
    elderTestimonial: {
      quote: 'Deepak brings me large-print books from the district library every fortnight.',
      elderName: 'Devaki Ammal (74)',
    },
  },
  {
    id: 'vol-8',
    name: 'Meera Chidambaram',
    phone: '+91 98408 90123',
    neighborhood: 'Anna Nagar',
    skills: ['Community Gardening', 'Art Therapy', 'Tamil'],
    languages: ['Tamil', 'English'],
    hoursContributed: 45,
    role: 'Balcony Gardening Ally',
    elderTestimonial: {
      quote: 'Meera brought potted jasmine for my balcony and reignited my love for gardening after two years of grief.',
      elderName: 'Lakshmi Rajagopalan (73)',
    },
  },
];

export const SEED_ACTIVITIES = [
  {
    id: 'act-1',
    title: 'Sunday Chai & Reminiscence Circle',
    category: 'social',
    categoryLabel: 'Social & Cultural',
    categoryColor: 'bg-amber-100 text-amber-800 border-amber-200',
    date: 'Weekly • Sundays 4:30 PM',
    location: 'Mylapore Cultural Mandapam',
    attendeesCount: 28,
    status: 'Ongoing',
    story: 'Over warm ginger tea and freshly roasted murukku, elderly citizens gathered to share oral histories of 1950s Madras. For many living alone, this is the single social event of their entire week.',
    elderQuote: {
      quote: 'When you grow old, you become invisible to the outside rush. Here, people look into your eyes and listen.',
      author: 'K. S. Narayana Swamy (82)',
      neighborhood: 'Mylapore',
    },
    communityOutcome: '28 seniors engaged; 4 new cross-street neighbor friendship circles formed.',
  },
  {
    id: 'act-2',
    title: 'Grandparent Smartphone & Cyber Safety Clinic',
    category: 'digital_literacy',
    categoryLabel: 'Digital Literacy',
    categoryColor: 'bg-blue-100 text-blue-800 border-blue-200',
    date: '2026-09-11',
    location: 'Anna Nagar West Library Hall',
    attendeesCount: 19,
    status: 'Completed',
    story: 'Young volunteer students paired one-on-one with seniors to teach WhatsApp video calling, auto-rickshaw booking, and recognizing spam bank calls without fear.',
    elderQuote: {
      quote: 'I used to be terrified of clicking buttons on my phone. Today I sent a voice note to my granddaughter in Chicago myself.',
      author: 'Padmavathi Sundar (71)',
      neighborhood: 'Anna Nagar',
    },
    communityOutcome: '19 elders now independently connected with family abroad via safe digital tools.',
  },
  {
    id: 'act-3',
    title: 'Doorstep Mobility & Geriatric Health Screening',
    category: 'health_camp',
    categoryLabel: 'Health & Wellness',
    categoryColor: 'bg-emerald-100 text-emerald-800 border-emerald-200',
    date: '2026-09-18',
    location: 'Adyar Community Hall & Mobile Van',
    attendeesCount: 35,
    status: 'Registration Open',
    story: 'Volunteer geriatricians and nurses provide free blood glucose checks, joint mobility consultations, vision screenings, and fall-prevention walking stick fittings.',
    elderQuote: {
      quote: 'Climbing government hospital stairs was impossible with my knees. Having the camp right on our street saved my life.',
      author: 'Shanti Ramanathan (78)',
      neighborhood: 'Mylapore',
    },
    communityOutcome: '35 elders registered; 12 flagged for follow-up home visits with physical therapists.',
  },
  {
    id: 'act-4',
    title: 'Digital Pension & Life Certificate (Jeevan Pramaan) Helpdesk',
    category: 'civic_services',
    categoryLabel: 'Civic & Legal Aid',
    categoryColor: 'bg-purple-100 text-purple-800 border-purple-200',
    date: 'Monthly • 1st Saturday',
    location: 'T. Nagar Seva Samithi',
    attendeesCount: 16,
    status: 'Completed',
    story: 'Coordinators with biometric iris scanners assisted elderly pensioners in submitting their annual digital life certificates without waiting in grueling queues.',
    elderQuote: {
      quote: 'I used to worry for weeks before November about standing at the treasury. The volunteers finished it in five minutes.',
      author: 'C. V. Radhakrishnan (80)',
      neighborhood: 'Velachery',
    },
    communityOutcome: '16 pension certificates renewed with zero treasury rejection errors.',
  },
  {
    id: 'act-5',
    title: 'Carnatic Music Therapy & Bhajan Sangam',
    category: 'social',
    categoryLabel: 'Social & Cultural',
    categoryColor: 'bg-amber-100 text-amber-800 border-amber-200',
    date: '2026-09-08',
    location: 'Triplicane Heritage Hall',
    attendeesCount: 22,
    status: 'Completed',
    story: 'A meditative musical afternoon where elders sang timeless Saint Thyagaraja and Purandara Dasa kritis accompanied by volunteer harmonium and mridangam players.',
    elderQuote: {
      quote: 'Singing in a chorus took away the heavy silence of my empty living room. My heart felt light again.',
      author: 'Rukmini Varadarajan (77)',
      neighborhood: 'Triplicane',
    },
    communityOutcome: '22 seniors participated; weekly community singing group established.',
  },
  {
    id: 'act-6',
    title: 'Chair Yoga, Balance & Fall Prevention Workshop',
    category: 'wellness',
    categoryLabel: 'Health & Wellness',
    categoryColor: 'bg-emerald-100 text-emerald-800 border-emerald-200',
    date: '2026-09-22',
    location: 'Royapettah YMCA Pavilion',
    attendeesCount: 24,
    status: 'Upcoming',
    story: 'Gentle seated stretching, diaphragmatic pranayama, and balance exercises specifically tailored for seniors with mild osteoporosis, stroke recovery, and arthritis.',
    elderQuote: {
      quote: 'I was afraid of falling every time I stood up from bed. Gentle breathing and chair exercises gave me my confidence back.',
      author: 'Mohanarangam (84)',
      neighborhood: 'Royapettah',
    },
    communityOutcome: 'Expected 24 seniors; tailored printed home exercise charts distributed.',
  },
];

export const SEED_BENEFICIARIES = [
  {
    id: 'ben-001',
    name: 'Shanti Ramanathan',
    age: 78,
    gender: 'Female',
    phone: '+91 98840 11223',
    neighborhood: 'Mylapore',
    address: '14/2 South Mada Street, Mylapore, Chennai',
    livingSituation: 'Lives Alone',
    emergencyContact: {
      name: 'Venkatesh Ramanathan',
      relationship: 'Son (Living in Bangalore)',
      phone: '+91 99401 88776',
    },
    status: 'needs_attention',
    lastInteractionDate: '2026-07-28',
    daysSinceContact: 47,
    assignedVolunteer: SEED_VOLUNTEERS[3], // Ananya Iyer
    needsAttentionReason: 'No contact in 47 days. Severe knee arthritis flare-up has prevented staircase descent from 2nd-floor home.',
    lifeStorySnippet: 'Former Carnatic vocal teacher and avid reader. After losing her husband 4 years ago, her living room is filled with classic music recordings and family portraits.',
    healthRemarks: 'Severe knee arthritis, mobility restricted to indoors, 2nd-floor walk-up with no elevator.',
    notesSummary: 'Gentle, polite, but very proud. Tends to downplay physical pain to avoid troubling volunteers. Needs proactive in-person check-in.',
    joinedDate: '2024-03-15',
    interactions: [
      {
        id: 'int-101',
        beneficiaryId: 'ben-001',
        type: 'phone_call',
        date: '2026-07-28',
        loggedBy: 'Coordinator Maya',
        notes: 'Sounded fatigued and quiet. Admitted knee stiffness made climbing down stairs impossible this month. Missed two Chai circles.',
        previousStatus: 'active',
        newStatus: 'needs_attention',
        followUpRequired: true,
      },
      {
        id: 'int-102',
        beneficiaryId: 'ben-001',
        type: 'volunteer_checkin',
        date: '2026-07-12',
        loggedBy: 'Volunteer Ananya Iyer',
        notes: 'Doorstep visit. Delivered weekly groceries, spent 40 minutes listening to vintage Carnatic ragas together. Spirits were high.',
      },
      {
        id: 'int-103',
        beneficiaryId: 'ben-001',
        type: 'event_attendance',
        date: '2026-06-25',
        loggedBy: 'Staff Rajesh',
        notes: 'Attended Sunday Chai & Chat circle. Smiled throughout and recited an old poem.',
      },
    ],
    activities: [
      { id: 'act-1', activityName: 'Sunday Chai & Reminiscence Circle', date: '2026-06-25', category: 'social', attended: true },
      { id: 'act-3', activityName: 'Doorstep Mobility & Geriatric Health Screening', date: '2026-05-20', category: 'health_camp', attended: true },
    ],
  },
  {
    id: 'ben-002',
    name: 'K. S. Narayana Swamy',
    age: 82,
    gender: 'Male',
    phone: '+91 94441 55667',
    neighborhood: 'T. Nagar',
    address: '22 Raman Street, Near Panagal Park, T. Nagar, Chennai',
    livingSituation: 'Lives Alone',
    emergencyContact: {
      name: 'Dr. Sudha Swamy',
      relationship: 'Daughter (Practicing Physician in Salem)',
      phone: '+91 98410 44332',
    },
    status: 'needs_attention',
    lastInteractionDate: '2026-08-05',
    daysSinceContact: 39,
    assignedVolunteer: SEED_VOLUNTEERS[1], // Rahul Nair
    needsAttentionReason: 'No check-in in 39 days. Last phone call rang twice and disconnected. Left ear hearing impairment.',
    lifeStorySnippet: 'Retired government high school headmaster. Passionate about Tamil literature, historical biographies, and evening radio news.',
    healthRemarks: 'Partial left ear hearing loss, mild hand tremors, prone to skipping meals when living alone.',
    notesSummary: 'Very articulate when engaged. Needs someone to physically knock loudly on his door since landline volume is often not heard.',
    joinedDate: '2023-11-10',
    interactions: [
      {
        id: 'int-201',
        beneficiaryId: 'ben-002',
        type: 'phone_call',
        date: '2026-08-05',
        loggedBy: 'Volunteer Rahul Nair',
        notes: 'Phone rang twice with no pickup. Need neighbor or volunteer physical check to verify safety.',
        previousStatus: 'active',
        newStatus: 'needs_attention',
        followUpRequired: true,
      },
      {
        id: 'int-202',
        beneficiaryId: 'ben-002',
        type: 'home_visit',
        date: '2026-07-02',
        loggedBy: 'Volunteer Rahul Nair',
        notes: 'Visited home. Swamy sir was in good health. Helped him fix his transistor radio batteries.',
      },
    ],
    activities: [
      { id: 'act-2', activityName: 'Grandparent Smartphone & Cyber Safety Clinic', date: '2026-06-18', category: 'digital_literacy', attended: true },
    ],
  },
  {
    id: 'ben-003',
    name: 'Devaki Ammal',
    age: 74,
    gender: 'Female',
    phone: '+91 97910 88990',
    neighborhood: 'Adyar',
    address: '8/1 Gandhi Nagar 3rd Crescent, Adyar, Chennai',
    livingSituation: 'With Spouse / Partner',
    emergencyContact: {
      name: 'R. Sundaram',
      relationship: 'Spouse (Age 79)',
      phone: '+91 97910 88991',
    },
    status: 'active',
    lastInteractionDate: '2026-09-10',
    daysSinceContact: 3,
    assignedVolunteer: SEED_VOLUNTEERS[2], // Sneha Reddy
    lifeStorySnippet: 'Matriarch of a close-knit neighborhood, co-founder of the local senior herb garden. Loves welcoming new volunteers.',
    healthRemarks: 'Mild hypertension managed with medication; active and mobile.',
    notesSummary: 'Devaki ji and her husband Sundaram are anchors of our Adyar circle. They actively encourage shy elders to attend.',
    joinedDate: '2024-01-20',
    interactions: [
      {
        id: 'int-301',
        beneficiaryId: 'ben-003',
        type: 'volunteer_checkin',
        date: '2026-09-10',
        loggedBy: 'Volunteer Sneha Reddy',
        notes: 'Weekly check-in. Devaki ji confirmed attendance for upcoming weekend chai circle.',
        newStatus: 'active',
      },
    ],
    activities: [
      { id: 'act-6', activityName: 'Chair Yoga, Balance & Fall Prevention Workshop', date: '2026-09-02', category: 'wellness', attended: true },
      { id: 'act-1', activityName: 'Sunday Chai & Reminiscence Circle', date: '2026-08-20', category: 'social', attended: true },
    ],
  },
  {
    id: 'ben-004',
    name: 'Syed Abdul Hameed',
    age: 85,
    gender: 'Male',
    phone: '+91 98845 66778',
    neighborhood: 'Triplicane',
    address: '45 Ellis Road, Triplicane, Chennai',
    livingSituation: 'Lives Alone',
    emergencyContact: {
      name: 'Farooq Hameed',
      relationship: 'Nephew',
      phone: '+91 98409 33221',
    },
    status: 'at_risk',
    lastInteractionDate: '2026-07-04',
    daysSinceContact: 71,
    assignedVolunteer: null, // Unassigned!
    needsAttentionReason: 'Critical Isolation Risk: 71 days without direct contact and NO assigned volunteer companion.',
    lifeStorySnippet: 'Master bookbinder who worked in heritage printing presses near Big Mosque. Lives alone in a quiet room behind the mosque courtyard.',
    healthRemarks: 'Diabetic, severe age-related frailty, reduced appetite, vision impairment in bright light.',
    notesSummary: 'Expressed feeling forgotten in last interaction. Urgently needs a local Triplicane volunteer companion to rebuild regular contact.',
    joinedDate: '2023-08-14',
    interactions: [
      {
        id: 'int-401',
        beneficiaryId: 'ben-004',
        type: 'phone_call',
        date: '2026-07-04',
        loggedBy: 'Staff Rajesh',
        notes: 'Spoke briefly. Sounded weak. Mentioned trouble walking to the local medical dispensary.',
        previousStatus: 'active',
        newStatus: 'at_risk',
        followUpRequired: true,
      },
    ],
    activities: [
      { id: 'act-5', activityName: 'Carnatic Music Therapy & Bhajan Sangam', date: '2026-05-10', category: 'social', attended: true },
    ],
  },
  {
    id: 'ben-005',
    name: 'Padmavathi Sundar',
    age: 71,
    gender: 'Female',
    phone: '+91 99620 33445',
    neighborhood: 'Anna Nagar',
    address: 'W-Block, 6th Main Road, Anna Nagar West, Chennai',
    livingSituation: 'Lives Alone',
    emergencyContact: {
      name: 'Gita Sundar',
      relationship: 'Daughter (Living in London, UK)',
      phone: '+44 7700 900123',
    },
    status: 'active',
    lastInteractionDate: '2026-09-08',
    daysSinceContact: 5,
    assignedVolunteer: SEED_VOLUNTEERS[0], // Priya Sharma
    lifeStorySnippet: 'Former primary school English educator. Deeply affectionate, loves storytelling, and makes traditional hand-knitted woolen scarves.',
    healthRemarks: 'Mild blood pressure, fully mobile and active.',
    notesSummary: 'Priya Sharma visits her weekly. The video calling workshop transformed her emotional outlook as she now speaks to her grandson weekly.',
    joinedDate: '2024-05-02',
    interactions: [
      {
        id: 'int-501',
        beneficiaryId: 'ben-005',
        type: 'volunteer_checkin',
        date: '2026-09-08',
        loggedBy: 'Volunteer Priya Sharma',
        notes: 'Doorstep visit. Padmavathi ji proudly showed photos of her video call with family in London. In great spirits.',
        newStatus: 'active',
      },
    ],
    activities: [
      { id: 'act-2', activityName: 'Grandparent Smartphone & Cyber Safety Clinic', date: '2026-09-11', category: 'digital_literacy', attended: true },
    ],
  },
  {
    id: 'ben-006',
    name: 'G. Balasubramanian',
    age: 79,
    gender: 'Male',
    phone: '+91 98412 77889',
    neighborhood: 'Velachery',
    address: '12 Dhandeeswaram Nagar 4th Cross, Velachery, Chennai',
    livingSituation: 'Lives Alone',
    emergencyContact: {
      name: 'Ravi Bala',
      relationship: 'Son (Working in Hyderabad)',
      phone: '+91 98410 99881',
    },
    status: 'needs_attention',
    lastInteractionDate: '2026-08-11',
    daysSinceContact: 33,
    assignedVolunteer: SEED_VOLUNTEERS[4], // Karthik Raman
    needsAttentionReason: '33 days since last contact. Recorded fluctuating blood pressure; missed scheduled medical follow-up.',
    lifeStorySnippet: 'Former port trust accountant. Meticulous with records, loves chess and morning walks along the lake.',
    healthRemarks: 'Fluctuating blood pressure, forgetfulness regarding medicine timings.',
    notesSummary: 'Needs volunteer Karthik to coordinate a doorstep pill organizer review with local pharmacy partner.',
    joinedDate: '2023-09-18',
    interactions: [
      {
        id: 'int-601',
        beneficiaryId: 'ben-006',
        type: 'event_attendance',
        date: '2026-08-11',
        loggedBy: 'Coordinator Maya',
        notes: 'Attended free BP check camp. Doctor noted elevated readings and advised re-check in 2 weeks.',
        previousStatus: 'active',
        newStatus: 'needs_attention',
        followUpRequired: true,
      },
    ],
    activities: [
      { id: 'act-3', activityName: 'Doorstep Mobility & Geriatric Health Screening', date: '2026-08-11', category: 'health_camp', attended: true },
    ],
  },
  {
    id: 'ben-007',
    name: 'Joseph Vijayaraj',
    age: 81,
    gender: 'Male',
    phone: '+91 98408 12399',
    neighborhood: 'Adyar',
    address: '7 Canal Bank Road, Kasturba Nagar, Adyar, Chennai',
    livingSituation: 'Lives Alone',
    emergencyContact: {
      name: 'Mary Vijayaraj',
      relationship: 'Sister (Lives in Tambaram)',
      phone: '+91 98400 66554',
    },
    status: 'at_risk',
    lastInteractionDate: '2026-06-20',
    daysSinceContact: 85,
    assignedVolunteer: SEED_VOLUNTEERS[2], // Sneha Reddy
    needsAttentionReason: 'Severe gap: 85 days without direct contact. Previous visit noted diminished appetite and profound loneliness.',
    lifeStorySnippet: 'Former physics tutor. Lives in ground floor room. His daily routine consists of tending to potted plants on his veranda.',
    healthRemarks: 'Recovering from mild cataract surgery, reported loss of appetite and low energy.',
    notesSummary: 'High priority for in-person companion outreach. Sneha Reddy assigned to visit with nutritious meals.',
    joinedDate: '2023-05-12',
    interactions: [
      {
        id: 'int-801',
        beneficiaryId: 'ben-007',
        type: 'volunteer_checkin',
        date: '2026-06-20',
        loggedBy: 'Volunteer Sneha Reddy',
        notes: 'Doorstep check. Joseph sir was quiet and ate very little. Expressed feeling isolated since his sister moved.',
        previousStatus: 'active',
        newStatus: 'at_risk',
        followUpRequired: true,
      },
    ],
    activities: [
      { id: 'act-3', activityName: 'Doorstep Mobility & Geriatric Health Screening', date: '2026-04-14', category: 'health_camp', attended: true },
    ],
  },
  {
    id: 'ben-008',
    name: 'Anthony D\'Souza',
    age: 84,
    gender: 'Male',
    phone: '+91 97909 33211',
    neighborhood: 'T. Nagar',
    address: '9 Habibullah Road, T. Nagar, Chennai',
    livingSituation: 'Lives Alone',
    status: 'inactive',
    lastInteractionDate: '2026-05-15',
    daysSinceContact: 121,
    assignedVolunteer: null,
    needsAttentionReason: 'Over 120 days disconnected. All relatives live out of state. Needs re-engagement evaluation.',
    lifeStorySnippet: 'Former railway signal technician. Skilled harmonica player, lived in T. Nagar for over 55 years.',
    healthRemarks: 'Mild memory lapses, arthritis.',
    notesSummary: 'Completely disconnected since May. Coordinator needs to do home verification visit with local church representative.',
    joinedDate: '2023-01-10',
    interactions: [],
    activities: [],
  },
];
