export const SEED_VOLUNTEERS = [
  { id: 'vol-1', name: 'Priya Sharma', phone: '+91 98401 23456', neighborhood: 'Anna Nagar', skills: ['Tamil', 'First Aid', 'Digital Skills'], languages: ['Tamil', 'English', 'Hindi'] },
  { id: 'vol-2', name: 'Rahul Nair', phone: '+91 98402 34567', neighborhood: 'T. Nagar', skills: ['Tamil', 'Malayalam', 'Elder Care'], languages: ['Tamil', 'Malayalam', 'English'] },
  { id: 'vol-3', name: 'Sneha Reddy', phone: '+91 98403 45678', neighborhood: 'Adyar', skills: ['Counseling', 'Telugu', 'Health Logistics'], languages: ['Telugu', 'Tamil', 'English'] },
  { id: 'vol-4', name: 'Ananya Iyer', phone: '+91 98404 56789', neighborhood: 'Mylapore', skills: ['Carnatic Arts', 'Tamil', 'Ration Assistance'], languages: ['Tamil', 'Sanskrit', 'English'] },
  { id: 'vol-5', name: 'Karthik Raman', phone: '+91 98405 67890', neighborhood: 'Velachery', skills: ['Government Schemes', 'Digital Literacy'], languages: ['Tamil', 'English'] },
];

export const SEED_ACTIVITIES = [
  {
    id: 'act-1',
    title: 'Chai & Chat Senior Social Circle',
    category: 'social',
    date: 'Weekly • Sundays 4:30 PM',
    location: 'Mylapore Community Center',
    attendeesCount: 28,
    status: 'Ongoing',
  },
  {
    id: 'act-2',
    title: 'Digital Literacy: Smartphone & Online Safety',
    category: 'digital_literacy',
    date: '2026-09-11',
    location: 'Anna Nagar Library Pavilion',
    attendeesCount: 19,
    status: 'Completed',
  },
  {
    id: 'act-3',
    title: 'Geriatric Health & Free Blood Pressure Camp',
    category: 'health_camp',
    date: '2026-09-18',
    location: 'Adyar Primary Health Pavilion',
    attendeesCount: 35,
    status: 'Registration Open',
  },
  {
    id: 'act-4',
    title: 'Pension & Civic Documentation Helpdesk',
    category: 'civic_services',
    date: 'Monthly • 1st Saturday',
    location: 'T. Nagar Seva Samithi',
    attendeesCount: 16,
    status: 'Completed',
  },
];

export const SEED_BENEFICIARIES = [
  {
    id: 'ben-001',
    name: 'Shanti Ramanathan',
    age: 78,
    gender: 'Female',
    phone: '+91 98840 11223',
    neighborhood: 'Mylapore',
    address: '14/2 South Mada Street, Mylapore, Chennai',
    livingSituation: 'Lives Alone',
    emergencyContact: {
      name: 'Venkatesh Ramanathan',
      relationship: 'Son (Bangalore)',
      phone: '+91 99401 88776',
    },
    status: 'needs_attention',
    lastInteractionDate: '2026-07-28',
    daysSinceContact: 47,
    assignedVolunteer: SEED_VOLUNTEERS[3], // Ananya Iyer
    needsAttentionReason: 'No contact in 45+ days. Missed two consecutive Sunday Chai & Chat circles.',
    notesSummary: 'Lives alone on 2nd floor with no elevator. Had mild arthritis flare-up last month.',
    joinedDate: '2024-03-15',
    interactions: [
      {
        id: 'int-101',
        beneficiaryId: 'ben-001',
        type: 'phone_call',
        date: '2026-07-28',
        loggedBy: 'Coordinator Maya',
        notes: 'Brief call. Sounded fatigued. Knee stiffness preventing staircase descent.',
        previousStatus: 'active',
        newStatus: 'needs_attention',
        followUpRequired: true,
      },
      {
        id: 'int-102',
        beneficiaryId: 'ben-001',
        type: 'volunteer_checkin',
        date: '2026-07-12',
        loggedBy: 'Volunteer Ananya Iyer',
        notes: 'Delivered monthly ration and chatted about Carnatic music.',
      },
    ],
    activities: [
      { id: 'act-1', activityName: 'Chai & Chat Social Circle', date: '2026-06-15', category: 'social', attended: true },
      { id: 'act-3', activityName: 'Geriatric Health Camp', date: '2026-05-20', category: 'health_camp', attended: true },
    ],
  },
  {
    id: 'ben-002',
    name: 'K. S. Narayana Swamy',
    age: 82,
    gender: 'Male',
    phone: '+91 94441 55667',
    neighborhood: 'T. Nagar',
    address: '22 Raman Street, Near Panagal Park, T. Nagar, Chennai',
    livingSituation: 'Lives Alone',
    emergencyContact: {
      name: 'Dr. Sudha Swamy',
      relationship: 'Daughter',
      phone: '+91 98410 44332',
    },
    status: 'needs_attention',
    lastInteractionDate: '2026-08-05',
    daysSinceContact: 39,
    assignedVolunteer: SEED_VOLUNTEERS[1], // Rahul Nair
    needsAttentionReason: 'No check-in in 39 days. Volunteer Rahul reported phone unanswered.',
    notesSummary: 'Retired school headmaster. Enjoys reading history books. Hearing impairment on left ear.',
    joinedDate: '2023-11-10',
    interactions: [
      {
        id: 'int-201',
        beneficiaryId: 'ben-002',
        type: 'phone_call',
        date: '2026-08-05',
        loggedBy: 'Volunteer Rahul Nair',
        notes: 'Phone rang twice, disconnected. Need to coordinate doorstep check.',
        previousStatus: 'active',
        newStatus: 'needs_attention',
        followUpRequired: true,
      },
    ],
    activities: [
      { id: 'act-2', activityName: 'Digital Literacy: Digital Banking & Safety', date: '2026-06-18', category: 'digital_literacy', attended: true },
    ],
  },
  {
    id: 'ben-003',
    name: 'Devaki Ammal',
    age: 74,
    gender: 'Female',
    phone: '+91 97910 88990',
    neighborhood: 'Adyar',
    address: '8/1 Gandhi Nagar 3rd Crescent, Adyar, Chennai',
    livingSituation: 'With Spouse / Partner',
    emergencyContact: {
      name: 'R. Sundaram (Spouse)',
      relationship: 'Spouse (Age 79)',
      phone: '+91 97910 88991',
    },
    status: 'active',
    lastInteractionDate: '2026-09-10',
    daysSinceContact: 3,
    assignedVolunteer: SEED_VOLUNTEERS[2], // Sneha Reddy
    notesSummary: 'Active community garden volunteer. Attends regular walks and gatherings.',
    joinedDate: '2024-01-20',
    interactions: [
      {
        id: 'int-301',
        beneficiaryId: 'ben-003',
        type: 'volunteer_checkin',
        date: '2026-09-10',
        loggedBy: 'Volunteer Sneha Reddy',
        notes: 'Weekly call check-in. Confirmed attendance for upcoming picnic.',
        newStatus: 'active',
      },
    ],
    activities: [
      { id: 'act-1', activityName: 'Chai & Chat Social Circle', date: '2026-09-02', category: 'social', attended: true },
    ],
  },
  {
    id: 'ben-004',
    name: 'Syed Abdul Hameed',
    age: 85,
    gender: 'Male',
    phone: '+91 98845 66778',
    neighborhood: 'Triplicane',
    address: '45 Ellis Road, Triplicane, Chennai',
    livingSituation: 'Lives Alone',
    emergencyContact: {
      name: 'Farooq Hameed',
      relationship: 'Nephew',
      phone: '+91 98409 33221',
    },
    status: 'at_risk',
    lastInteractionDate: '2026-07-04',
    daysSinceContact: 71,
    assignedVolunteer: null,
    needsAttentionReason: 'High Isolation Risk: 71 days without direct contact and NO assigned volunteer.',
    notesSummary: 'Has diabetes and hypertension. Living in independent room behind mosque.',
    joinedDate: '2023-08-14',
    interactions: [
      {
        id: 'int-401',
        beneficiaryId: 'ben-004',
        type: 'phone_call',
        date: '2026-07-04',
        loggedBy: 'Staff Rajesh',
        notes: 'Spoke briefly. Requested assistance with renewing his pensioner card.',
        previousStatus: 'active',
        newStatus: 'at_risk',
        followUpRequired: true,
      },
    ],
    activities: [
      { id: 'act-4', activityName: 'Pension & Civic Service Helpdesk', date: '2026-05-10', category: 'civic_services', attended: true },
    ],
  },
  {
    id: 'ben-005',
    name: 'Padmavathi Sundar',
    age: 71,
    gender: 'Female',
    phone: '+91 99620 33445',
    neighborhood: 'Anna Nagar',
    address: 'W-Block, 6th Main Road, Anna Nagar West, Chennai',
    livingSituation: 'Lives Alone',
    emergencyContact: {
      name: 'Gita Sundar',
      relationship: 'Daughter (UK)',
      phone: '+44 7700 900123',
    },
    status: 'active',
    lastInteractionDate: '2026-09-08',
    daysSinceContact: 5,
    assignedVolunteer: SEED_VOLUNTEERS[0], // Priya Sharma
    notesSummary: 'Enjoys teaching English and storytelling. Regular attendee of weekly circles.',
    joinedDate: '2024-05-02',
    interactions: [
      {
        id: 'int-501',
        beneficiaryId: 'ben-005',
        type: 'volunteer_checkin',
        date: '2026-09-08',
        loggedBy: 'Volunteer Priya Sharma',
        notes: 'Doorstep visit with groceries. Padmavathi ji is doing very well.',
        newStatus: 'active',
      },
    ],
    activities: [
      { id: 'act-1', activityName: 'Chai & Chat Social Circle', date: '2026-09-01', category: 'social', attended: true },
    ],
  },
  {
    id: 'ben-006',
    name: 'G. Balasubramanian',
    age: 79,
    gender: 'Male',
    phone: '+91 98412 77889',
    neighborhood: 'Velachery',
    address: '12 Dhandeeswaram Nagar 4th Cross, Velachery, Chennai',
    livingSituation: 'Lives Alone',
    emergencyContact: {
      name: 'Ravi Bala',
      relationship: 'Son',
      phone: '+91 98410 99881',
    },
    status: 'needs_attention',
    lastInteractionDate: '2026-08-11',
    daysSinceContact: 33,
    assignedVolunteer: SEED_VOLUNTEERS[4], // Karthik Raman
    needsAttentionReason: 'Over 30 days without contact. Missed routine blood pressure monitoring follow-up.',
    notesSummary: 'Former port trust employee. Mild memory issues reported by neighbors.',
    joinedDate: '2023-09-18',
    interactions: [
      {
        id: 'int-601',
        beneficiaryId: 'ben-006',
        type: 'event_attendance',
        date: '2026-08-11',
        loggedBy: 'Coordinator Maya',
        notes: 'Attended free BP check camp. Fluctuating readings.',
        previousStatus: 'active',
        newStatus: 'needs_attention',
        followUpRequired: true,
      },
    ],
    activities: [
      { id: 'act-3', activityName: 'Geriatric Health Camp', date: '2026-08-11', category: 'health_camp', attended: true },
    ],
  },
  {
    id: 'ben-007',
    name: 'Joseph Vijayaraj',
    age: 81,
    gender: 'Male',
    phone: '+91 98408 12399',
    neighborhood: 'Adyar',
    address: '7 Canal Bank Road, Kasturba Nagar, Adyar, Chennai',
    livingSituation: 'Lives Alone',
    status: 'at_risk',
    lastInteractionDate: '2026-06-20',
    daysSinceContact: 85,
    assignedVolunteer: SEED_VOLUNTEERS[2], // Sneha Reddy
    needsAttentionReason: 'Critical gap: 85 days since last contact. Reduced appetite noted.',
    notesSummary: 'Former teacher. Recovering from mild cataract surgery.',
    joinedDate: '2023-05-12',
    interactions: [
      {
        id: 'int-801',
        beneficiaryId: 'ben-007',
        type: 'volunteer_checkin',
        date: '2026-06-20',
        loggedBy: 'Volunteer Sneha Reddy',
        notes: 'Doorstep visit. Mentioned feeling lonely.',
        previousStatus: 'active',
        newStatus: 'at_risk',
        followUpRequired: true,
      },
    ],
    activities: [
      { id: 'act-3', activityName: 'Geriatric Health Camp', date: '2026-04-14', category: 'health_camp', attended: true },
    ],
  },
  {
    id: 'ben-008',
    name: 'Anthony D\'Souza',
    age: 84,
    gender: 'Male',
    phone: '+91 97909 33211',
    neighborhood: 'T. Nagar',
    address: '9 Habibullah Road, T. Nagar, Chennai',
    livingSituation: 'Lives Alone',
    status: 'inactive',
    lastInteractionDate: '2026-05-15',
    daysSinceContact: 121,
    assignedVolunteer: null,
    needsAttentionReason: 'No contact for 120+ days. Disconnected from all community programs.',
    notesSummary: 'Living alone. Relatives in Goa. Has not participated since May.',
    joinedDate: '2023-01-10',
    interactions: [],
    activities: [],
  },
];
